steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/test-project-23p/test-23p-app:$SHORT_SHA', '.' ]
# push container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-project-23p/test-23p-app:$SHORT_SHA']
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=test-23p-deployment.yml
  - --image=gcr.io/test-project-23p/test-23p-app:$SHORT_SHA
  - --location=us-central1-a
  - --cluster=test-23p-cluster
